### ISSUE TITLE
Plus one regexp

### ISSUE THREAD

**Issue by LTe** [LTe/muzang#2]
I have to create a kick ass regular expression. Can you give examples of that bot should recognize, and which not?

Key example (should work)

```
<mlomnicki> [awesome text]
<LTe> mlomnicki: +1
<DRUG-bot> *LTe* podarowal +1 dla mlomnicki
```

**Should work**

```
github: +1
github +1
github: +1 for you!
github +1 for you!
```

**Should not work**

```
github: you know what, +1 is very very very awesome feature
github: 1+1=2
```

etc :)

**Comment by mostlyobvious** [comment]
> mlomnicki [awesome text]

this is bad by design

**Comment by LTe** [comment]
Refactor.
